In [36]:
import pandas as pd
import numpy as np

In [2]:
thq = pd.read_csv("THQ.csv")
cr = pd.read_csv("CR.csv")

In [5]:
cols = ['THQA Cr', 'THQA Mn', 'THQA Fe', 'THQA Co', 'THQA Ni', 'THQA Cu',
       'THQA Zn', 'THQA Cd', 'THQA Pb', 'HI Adults', 'THQC Cr', 'THQC Mn',
       'THQC Fe', 'THQC Co', 'THQC Ni', 'THQC Cu', 'THQC Zn', 'THQC Cd',
       'THQC Pb', 'HI Children']

In [6]:
thq.columns = cols
thq

THQA Cr   THQA Mn   THQA Fe   THQA Co   THQA Ni   THQA Cu   THQA Zn  \
0  0.064570  2.273133  1.742947  1.595643  0.061138  0.451781  0.750143   
1  0.030605  1.778184  0.359578  1.258714  0.071836  0.801000  1.006971   
2  0.025973  2.691796  1.664845  3.573350  0.047597  0.780233  0.351804   
3  0.090090  7.631296  0.508390  3.162043  0.044273  0.759467  0.233900   
4  0.022613  6.806684  1.359157  1.978343  0.039233  0.378462  0.405120   
5  0.028062  5.930306  1.388945  3.263121  0.052510  0.318747  0.387786   

    THQA Cd   THQA Pb  HI Adults   THQC Cr    THQC Mn   THQC Fe  THQC Co  \
0  0.094994  0.979000   8.013348  0.101571   3.575714  2.741714    2.510   
1  0.142400  1.468500   6.917788  0.048143   2.797143  0.565629    1.980   
2  0.247202  1.347714  10.730520  0.040857   4.234286  2.618857    5.621   
3  0.151118  4.094000  16.674580  0.141714  12.004290  0.799714    4.974   
4  0.128233  1.799071  12.916920  0.035571  10.707140  2.138000    3.112   
5  0.117516  6.166429  17.653420  0.044143   9.328571  2.184857    5.133   

    THQC Ni   THQC Cu   THQC Zn   THQC Cd   THQC Pb  HI Children  
0  0.096171  0.152286  1.180000  0.034867  0.044000    10.436320  
1  0.113000  0.270000  1.584000  0.052267  0.066000     7.476181  
2  0.074871  0.263000  0.553400  0.090733  0.060571    13.557580  
3  0.069643  0.256000  0.367933  0.055467  0.184000    18.852760  
4  0.061714  0.127571  0.637267  0.047067  0.080857    16.947190  
5  0.082600  0.107443  0.610000  0.043133  0.277143    17.810890

In [7]:
cr

CRA Cr    CRA Co    CRA Cd    CRA Pb    CRA Ni    CRC Cr    CRC Co  \
0  0.004197  0.290407  0.000023  0.000016  0.135114  0.000609  0.042168   
1  0.001989  0.229086  0.000035  0.000023  0.158757  0.000289  0.033264   
2  0.001688  0.650350  0.000061  0.000021  0.105189  0.000245  0.094433   
3  0.005856  0.575492  0.000037  0.000065  0.097843  0.000850  0.083563   
4  0.001470  0.360058  0.000032  0.000028  0.086704  0.000213  0.052282   
5  0.001824  0.593888  0.000029  0.000097  0.116047  0.000265  0.086234   

     CRC Cd    CRC Pb    CRC Ni  
0  0.000003  0.000002  0.019619  
1  0.000005  0.000003  0.023052  
2  0.000009  0.000003  0.015274  
3  0.000005  0.000009  0.014207  
4  0.000005  0.000004  0.012590  
5  0.000004  0.000014  0.016850

In [23]:
newcols = ['Cr THQA',
 'Mn THQA',
 'Fe THQA',
 'Co THQA',
 'Ni THQA',
 'Cu THQA',
 'Zn THQA',
 'Cd THQA',
 'Pb THQA',
 'HI Adults',
 'Cr THQC',
 'Mn THQC',
 'Fe THQC',
 'Co THQC',
 'Ni THQC',
 'Cu THQC',
 'Zn THQC',
 'Cd THQC',
 'Pb THQC',
 'HI Children']

In [24]:
thq.columns = newcols

In [25]:
thq

Cr THQA   Mn THQA   Fe THQA   Co THQA   Ni THQA   Cu THQA   Zn THQA  \
0  0.064570  2.273133  1.742947  1.595643  0.061138  0.451781  0.750143   
1  0.030605  1.778184  0.359578  1.258714  0.071836  0.801000  1.006971   
2  0.025973  2.691796  1.664845  3.573350  0.047597  0.780233  0.351804   
3  0.090090  7.631296  0.508390  3.162043  0.044273  0.759467  0.233900   
4  0.022613  6.806684  1.359157  1.978343  0.039233  0.378462  0.405120   
5  0.028062  5.930306  1.388945  3.263121  0.052510  0.318747  0.387786   

    Cd THQA   Pb THQA  HI Adults   Cr THQC    Mn THQC   Fe THQC  Co THQC  \
0  0.094994  0.979000   8.013348  0.101571   3.575714  2.741714    2.510   
1  0.142400  1.468500   6.917788  0.048143   2.797143  0.565629    1.980   
2  0.247202  1.347714  10.730520  0.040857   4.234286  2.618857    5.621   
3  0.151118  4.094000  16.674580  0.141714  12.004290  0.799714    4.974   
4  0.128233  1.799071  12.916920  0.035571  10.707140  2.138000    3.112   
5  0.117516  6.166429  17.653420  0.044143   9.328571  2.184857    5.133   

    Ni THQC   Cu THQC   Zn THQC   Cd THQC   Pb THQC  HI Children  
0  0.096171  0.152286  1.180000  0.034867  0.044000    10.436320  
1  0.113000  0.270000  1.584000  0.052267  0.066000     7.476181  
2  0.074871  0.263000  0.553400  0.090733  0.060571    13.557580  
3  0.069643  0.256000  0.367933  0.055467  0.184000    18.852760  
4  0.061714  0.127571  0.637267  0.047067  0.080857    16.947190  
5  0.082600  0.107443  0.610000  0.043133  0.277143    17.810890

In [71]:
cr

CRA Cr    CRA Co    CRA Cd    CRA Pb    CRA Ni    CRC Cr    CRC Co  \
0  0.004197  0.290407  0.000023  0.000016  0.135114  0.000609  0.042168   
1  0.001989  0.229086  0.000035  0.000023  0.158757  0.000289  0.033264   
2  0.001688  0.650350  0.000061  0.000021  0.105189  0.000245  0.094433   
3  0.005856  0.575492  0.000037  0.000065  0.097843  0.000850  0.083563   
4  0.001470  0.360058  0.000032  0.000028  0.086704  0.000213  0.052282   
5  0.001824  0.593888  0.000029  0.000097  0.116047  0.000265  0.086234   

     CRC Cd    CRC Pb    CRC Ni  
0  0.000003  0.000002  0.019619  
1  0.000005  0.000003  0.023052  
2  0.000009  0.000003  0.015274  
3  0.000005  0.000009  0.014207  
4  0.000005  0.000004  0.012590  
5  0.000004  0.000014  0.016850

In [37]:
arrthq = np.array(thq)

In [41]:
len(arrthq[0])

20

In [40]:
thq.shape

(6, 20)

In [45]:
tarr = arrthq.T

In [47]:
tarr[0]

array([0.06457 , 0.030605, 0.025973, 0.09009 , 0.022613, 0.028062])

In [56]:
tarr[1]

array([2.273133, 1.778184, 2.691796, 7.631296, 6.806684, 5.930306])

In [53]:
hival = []
for i in range(len(tarr)):
    for j in range(6):
        hival.append(tarr[i][j])

In [57]:
len(hival)

120

In [58]:
arrcr = np.array(cr)

In [59]:
carr = arrcr.T

In [60]:
carr.shape

(10, 6)

In [61]:
carr

array([[4.19700e-03, 1.98900e-03, 1.68800e-03, 5.85600e-03, 1.47000e-03,
        1.82400e-03],
       [2.90407e-01, 2.29086e-01, 6.50350e-01, 5.75492e-01, 3.60058e-01,
        5.93888e-01],
       [2.35000e-05, 3.52000e-05, 6.11000e-05, 3.73000e-05, 3.17000e-05,
        2.90000e-05],
       [1.55000e-05, 2.32000e-05, 2.13000e-05, 6.46000e-05, 2.84000e-05,
        9.73000e-05],
       [1.35114e-01, 1.58757e-01, 1.05189e-01, 9.78430e-02, 8.67040e-02,
        1.16047e-01],
       [6.09000e-04, 2.89000e-04, 2.45000e-04, 8.50000e-04, 2.13000e-04,
        2.65000e-04],
       [4.21680e-02, 3.32640e-02, 9.44330e-02, 8.35630e-02, 5.22820e-02,
        8.62340e-02],
       [3.41000e-06, 5.11000e-06, 8.87000e-06, 5.42000e-06, 4.60000e-06,
        4.21000e-06],
       [2.24000e-06, 3.37000e-06, 3.09000e-06, 9.38000e-06, 4.12000e-06,
        1.41000e-05],
       [1.96190e-02, 2.30520e-02, 1.52740e-02, 1.42070e-02, 1.25900e-02,
        1.68500e-02]])

In [62]:
crval = []
for i in range(len(carr)):
    for j in range(6):
        crval.append(carr[i][j])

In [64]:
len(crval)

60

In [66]:
hival = pd.Series(hival)
crval = pd.Series(crval)

In [68]:
hicr = pd.concat([hival,crval])

In [98]:
df = pd.DataFrame({
        "Values": hicr
})

In [99]:
cols

['THQA Cr',
 'THQA Mn',
 'THQA Fe',
 'THQA Co',
 'THQA Ni',
 'THQA Cu',
 'THQA Zn',
 'THQA Cd',
 'THQA Pb',
 'HI Adults',
 'THQC Cr',
 'THQC Mn',
 'THQC Fe',
 'THQC Co',
 'THQC Ni',
 'THQC Cu',
 'THQC Zn',
 'THQC Cd',
 'THQC Pb',
 'HI Children']

In [100]:
m = []

labels = ["Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Cd", "Pb", "HI", 
          "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Cd", "Pb", "HI"]

for label in labels:
    for _ in range(6):    
        m.append(label)

In [101]:
labels = ["Cr", "Co","Cd","Pb", "Ni",
          "Cr", "Co","Cd","Pb", "Ni"]

for label in labels:
    for _ in range(6):    
        m.append(label)

In [102]:
len(m)

180

In [103]:
df["Param"] = m

In [104]:
df

Values Param
0   0.064570    Cr
1   0.030605    Cr
2   0.025973    Cr
3   0.090090    Cr
4   0.022613    Cr
..       ...   ...
55  0.023052    Ni
56  0.015274    Ni
57  0.014207    Ni
58  0.012590    Ni
59  0.016850    Ni

[180 rows x 2 columns]

In [105]:
m = []

for _ in range(60):
    m.append("Adult")
for _ in range(60):
    m.append("Child")

for _ in range(30):
    m.append("Adult")
for _ in range(30):
    m.append("Child")

In [106]:
df["Age"] = m

In [107]:
df

Values Param    Age
0   0.064570    Cr  Adult
1   0.030605    Cr  Adult
2   0.025973    Cr  Adult
3   0.090090    Cr  Adult
4   0.022613    Cr  Adult
..       ...   ...    ...
55  0.023052    Ni  Child
56  0.015274    Ni  Child
57  0.014207    Ni  Child
58  0.012590    Ni  Child
59  0.016850    Ni  Child

[180 rows x 3 columns]

In [108]:
m = []

for _ in range(54):
    m.append("THQ")
for _ in range(6):
    m.append("HI")

for _ in range(54):
    m.append("THQ")
for _ in range(6):
    m.append("HI")

for _ in range(60):
    m.append("CR")

In [109]:
df.columns = ["y", "Metals", "Age"]
df

y Metals    Age
0   0.064570     Cr  Adult
1   0.030605     Cr  Adult
2   0.025973     Cr  Adult
3   0.090090     Cr  Adult
4   0.022613     Cr  Adult
..       ...    ...    ...
55  0.023052     Ni  Child
56  0.015274     Ni  Child
57  0.014207     Ni  Child
58  0.012590     Ni  Child
59  0.016850     Ni  Child

[180 rows x 3 columns]

In [110]:
df["Param"] = m

In [111]:
df

y Metals    Age Param
0   0.064570     Cr  Adult   THQ
1   0.030605     Cr  Adult   THQ
2   0.025973     Cr  Adult   THQ
3   0.090090     Cr  Adult   THQ
4   0.022613     Cr  Adult   THQ
..       ...    ...    ...   ...
55  0.023052     Ni  Child    CR
56  0.015274     Ni  Child    CR
57  0.014207     Ni  Child    CR
58  0.012590     Ni  Child    CR
59  0.016850     Ni  Child    CR

[180 rows x 4 columns]

In [112]:
paramage = df.Param + " " + df.Age

In [113]:
paramage

0     THQ Adult
1     THQ Adult
2     THQ Adult
3     THQ Adult
4     THQ Adult
        ...    
55     CR Child
56     CR Child
57     CR Child
58     CR Child
59     CR Child
Length: 180, dtype: object

In [114]:
df["ParamAge"] = paramage

In [115]:
df.to_csv("data.csv")

In [118]:
hi = df[:120]
cr = df[120:]

In [119]:
hi.to_csv("data_hi.csv")
cr.to_csv("data_cr.csv")

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df

Unnamed: 0         y Metals    Age Param   ParamAge
0             0  0.064570     Cr  Adult   THQ  THQ Adult
1             1  0.030605     Cr  Adult   THQ  THQ Adult
2             2  0.025973     Cr  Adult   THQ  THQ Adult
3             3  0.090090     Cr  Adult   THQ  THQ Adult
4             4  0.022613     Cr  Adult   THQ  THQ Adult
..          ...       ...    ...    ...   ...        ...
175          55  0.023052     Ni  Child    CR   CR Child
176          56  0.015274     Ni  Child    CR   CR Child
177          57  0.014207     Ni  Child    CR   CR Child
178          58  0.012590     Ni  Child    CR   CR Child
179          59  0.016850     Ni  Child    CR   CR Child

[180 rows x 6 columns]

In [7]:
new_df = df[df.Param !=  "HI"]

In [8]:
new_df

Unnamed: 0         y Metals    Age Param   ParamAge
0             0  0.064570     Cr  Adult   THQ  THQ Adult
1             1  0.030605     Cr  Adult   THQ  THQ Adult
2             2  0.025973     Cr  Adult   THQ  THQ Adult
3             3  0.090090     Cr  Adult   THQ  THQ Adult
4             4  0.022613     Cr  Adult   THQ  THQ Adult
..          ...       ...    ...    ...   ...        ...
175          55  0.023052     Ni  Child    CR   CR Child
176          56  0.015274     Ni  Child    CR   CR Child
177          57  0.014207     Ni  Child    CR   CR Child
178          58  0.012590     Ni  Child    CR   CR Child
179          59  0.016850     Ni  Child    CR   CR Child

[168 rows x 6 columns]

In [10]:
new_df.Metals.unique()

array(['Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Cd', 'Pb'], dtype=object)

In [11]:
cr = new_df[new_df.Metals == "Cr"]
mn = new_df[new_df.Metals == "Mn"]
fe = new_df[new_df.Metals == "Fe"]
co = new_df[new_df.Metals == "Co"]
ni = new_df[new_df.Metals == "Ni"]
cu = new_df[new_df.Metals == "Cu"]
zn = new_df[new_df.Metals == "Zn"]
cd = new_df[new_df.Metals == "Cd"]
pb = new_df[new_df.Metals == "Pb"]


In [13]:
gen = pd.concat([fe,mn,cr,co,ni,cd,pb,zn,cu])

In [14]:
gen.to_csv("Generate.csv")